CREATE TABLE Comments(
    id INT AUTO_INCREMENT PRIMARY KEY ,
    name VARCHAR(255),
    comment TEXT,
    posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Cart(
  id INT AUTO_INCREMENT PRIMARY KEY ,
  product_id INT,
  quantity INT,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);